apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-build-config
spec:
  runPolicy: Serial
  source:
      git:
        ref: master
        uri: https://github.com/DipakKasar2/WebApp.git
      type: Git
  strategy:
      dockerStrategy:
      type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-webapp-docker:latest'
  triggers:
    - type: ConfigChange

